const js = require("@eslint/js");

module.exports = [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        atob: "readonly",
        btoa: "readonly",
        crypto: "readonly",
        performance: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        indexedDB: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
        Image: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Promise: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        Symbol: "readonly",
        Uint8Array: "readonly",
        ArrayBuffer: "readonly",
        DataView: "readonly",
        structuredClone: "readonly",
        queueMicrotask: "readonly",
        location: "readonly",
        history: "readonly",
        self: "readonly",

        // Chrome extension APIs
        chrome: "readonly",
        importScripts: "readonly",
        // Set by importScripts(...) in sw.js before use.
        ExtPay: "readonly",
        SUEntitlement: "readonly",
        // Browser globals missing from the list above.
        prompt: "readonly",
        DecompressionStream: "readonly",
        requestIdleCallback: "readonly",
        cancelIdleCallback: "readonly",
      },
    },
    rules: {
      // Relax rules for a large existing codebase
      "no-unused-vars": ["warn", { args: "none", caughtErrors: "none" }],
      "no-empty": "warn",
      "no-console": "off",
    },
  },
  {
    // Real ES modules (import/export) — everything else in src/ is a classic
    // script loaded via <script>, importScripts(), or dynamic import().
    files: [
      "src/common/storage.js",
      "src/common/quality.js",
      "src/common/entitlement.js",
      "src/content/content-author.js",
      "src/content/data-loader.js",
      "src/content/dom-cache.js",
      "src/content/genealogy-lineage.js",
      "src/content/trend-methods.js",
      "src/content/trend-tracker.js",
      "src/library/library.js",
      "src/options/options.js",
      "src/popup/popup.js",
    ],
    languageOptions: {
      sourceType: "module",
    },
  },
  {
    // Vendored third-party library — not our lint debt to fix.
    ignores: ["dist/**", "node_modules/**", "src/data/**", "src/common/extpay.js"],
  },
];
